### ISSUE TITLE
editor hangs when switching to module

### ISSUE THREAD

**Issue by Flippo24** [retejs/readonly-plugin#1]
The editor wont clear, when switching to a module1.rete. I used the module example an added the readonly module from jsdelivr.

![grafik](https://user-images.githubusercontent.com/5230426/41715029-71f03386-7552-11e8-9b30-88758afaaacd.png)

when switching back to index.rete, browser hangs...

Same on Chrome and Firefox.

**Comment by Ni55aN** [comment]
Fixed: https://github.com/retejs/rete/commit/82fec077edb7f2dc280d74309dabb5492d92f953

Will be publised soon. 

Now try
````js
async function openModule(name) {
    currentModule.data = editor.toJSON();
    
    currentModule = modules[name];
    editor.silent = true; // hot fix
    await editor.fromJSON(currentModule.data);
}
````

**Comment by Flippo24** [comment]
:thumbsup: Fixed! Thanks.
